# Site settings
title: Carolyn Dew | UX Design and Research
email: carolyndew@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I&rsquo;m a UX/graphic designer with experience in web and print design, with particular experience serving nonprofit and socially responsible businesses.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://127.0.0.1:4000" # the base hostname & protocol for your site
twitter_username: carodew
# github_username:  jekyll

# Build settings
markdown: kramdown

# defaults:
#   -
#     scope:
#       path: ""
#     values:
#       img-path: "../img/" # overrides previous default layout
